### PR TITLE
Type Load fix, removed deprecated packages, added replacement packages…

### PR DESCRIPTION
**Pull request by jericsmith**
…fixed tests, cleaned usings, removed unused references

### CODE REVIEW

**Comment by glennblock** [comment]
@jericsmith thanks for doing the work here and sending the PR.

One thing I am concerned with is looking at the file changes,  it looks like every file has been replaced rather than just the deltas. I can see that you've made changes, but it should replace the entire files. I wonder if maybe there's a tab/spaces thing or something going on as in some cases the replacement looks identical barring some minor changes.

**Comment by jericsmith** [comment]
I tried to cheat after effing up references.  I'll fix and do another pr.  Thx.

--- Original Message ---

**Comment by glennblock** [comment]
Thank you!

**Comment by jericsmith** [comment]
I just requested another PR (using original forked files this time).  Also, I only bothered cleaning up the usings in the files that were changed with the package upgrades/test fixes.  Again, excellent book; thanks for that.
Eric Smith

Date: Sun, 28 Sep 2014 17:17:08 -0700

**Pull request closed without merging**
