### PR TITLE
Acceptance tests clean up

### PR DESCRIPTION
**Pull request by adamralph**
- aligned tabulation of step bodies
- added readonly to fields
- converted step to "And..." where appropriate
- removed redundant usings
- removed redundant blank lines
- made abstract type constructors protected
- converted list creation to initializer

### CODE REVIEW

**Comment by adamralph** [comment]
Is there any interest in this? Do you even take PR's for this repo? :smile:

**Comment by glennblock** [comment]
Yes...will look at ir

**Comment by glennblock** [comment]
OK @adamralph I see this just tests and you know your own framework so I trust your judgment. Thanks a ton and no I did not forget!

:+1:

**Comment by glennblock** [comment]
I hope a "better late than never" merge is acceptable :-)

**Comment by glennblock** [comment]
OK, now looking more deeply at the PR, the one concern I have is that the renames of the test steps break with the book. That makes it more difficult for one to jump between them. I've been cautious of this. I may revert back the names for that reason.

As to the formatting of the lambdas, R# did that for me, but that is really in the eye of the beholder.

The rest of the cleanup is fine.

**Pull request merged**
